# Generated by Django 4.1.7 on 2023-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlanner', '0006_alter_recipe_description_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'breakfast'), ('Lunch', 'lunch'), ('Dinner', 'dinner')], max_length=20),
        ),
    ]
